name: Gradle Publish

on:
  workflow_call:
    inputs:
      jdk_version:
        description: "JDK version"
        type: number
        required: true
      jdk_distribution:
        description: "JVM distribution"
        type: string
        required: true

      publish_to_maven_github_packages:
        description: "Is Maven Repository GitHub Packages"
        type: boolean
        required: false
        default: false

      binaries_artifact_name:
        description: "Binaries artifact name"
        type: string
        required: false
        default: binaries

jobs:
  publish-to-maven:
    name: Publish to Maven
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/download-artifact@v4
        name: Download build artifacts
        with:
          name: ${{ inputs.binaries_artifact_name }}
          path: build/libs

      - uses: actions/setup-java@v4
        name: Set up JDK
        with:
          java-version: ${{ inputs.jdk_version }}
          distribution: ${{ inputs.jdk_distribution }}

      - uses: gradle/actions/setup-gradle@v4
        name: Set up Gradle

      - name: Publish to Maven
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ inputs.publish_to_maven_github_packages && secrets.GITHUB_TOKEN || '' }}